Lots of little things
TechMCDocs/TechMCDocs.github.io pull request #16
Opened 2022-03-05 17:50 UTC by polarbub

Lots of little things to make the experience more cohesive

Change list:
- Add Favicon
- Clean up wording 
- Fix version selection
-

2022-03-05 21:45 UTC, polarbub commented
Also this requires my other [pr](https://github.com/TechMCDocs/pages/pull/11) to pages

2022-03-06 18:49 UTC, Earthcomputer requested changes
Please remove the update to the pages submodule from the PR, this is updated automatically by GitHub actions

2022-03-08 00:12 UTC, polarbub commented
It took me six tries and a lot of rewriting commit history (just my own commits) but I got the pages submodule back to commit 2507321. That's the commit it was on when I started.

2022-03-15 23:56 UTC, Earthcomputer approved these changes

2022-03-16 18:11 UTC, merged